import type { Metadata } from "next";
import { Geist, Geist_Mono, Rethink_Sans, Italianno } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const italianno = Italianno({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-script",
  display: "swap",
});

const rethinkSans = Rethink_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SmoothScroll } from "@/components/providers/smooth-scroll";

import { Navbar } from "@/components/navbar";

import { ScrollToTop } from "@/components/scroll-to-top";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, rethinkSans.variable, italianno.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col bg-[linear-gradient(164.34deg,#FFFFFF_-18.24%,#D3FBFD_-6.6%,#EFF1FD_25.14%,#FFFFFF_77.86%)] 2xl:container 2xl:mx-auto">
        <SmoothScroll>
          <ScrollToTop />
          <Navbar />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
